#  ______ _ _       _     _    _____            _             _ 
# |  ____| (_)     | |   | |  / ____|          | |           | |
# | |__  | |_  __ _| |__ | |_| |     ___  _ __ | |_ _ __ ___ | |
# |  __| | | |/ _` | '_ \| __| |    / _ \| '_ \| __| '__/ _ \| |
# | |    | | | (_| | | | | |_| |___| (_) | | | | |_| | | (_) | |
# |_|    |_|_|\__, |_| |_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
#              __/ |                                            
#             |___/                                    By Spazzinq

# Before leaving a negative or neutral review, you should first read through the information on this configuration
# and then contact me on Discord if the configuration does not note your problem (below is my Discord link :D)
# https://spazzinq.org/discord

#   ____             __ _                       _   _             
#  / ___|___  _ __  / _(_) __ _ _   _ _ __ __ _| |_(_) ___  _ __  
# | |   / _ \| '_ \| |_| |/ _` | | | | '__/ _` | __| |/ _ \| '_ \ 
# | |__| (_) | | | |  _| | (_| | |_| | | | (_| | |_| | (_) | | | |
#  \____\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\__|_|\___/|_| |_|
#                         |___/                                                   

# If you do not wish to use certain options, leave the examples as they are
# If you want to add more worlds, regions, categories, or faction territories to be controlled, carefully copy and paste the given examples so they line up with the previous entries
# Example Video: https://www.youtube.com/watch?v=SnHCX9yn2XA

# This feature requires CombatTagPlus, CombatLogX, or AntiCombatLogging!
# Disable the option to stop flight in the combat plugin configuration to prevent issues
# Set the following value to true if you wish to disable flight in combat
disable_flight_in_combat: false

# Set the following value to true if you wish for players to not take fall damage if their flight is disabled by FlightControl
disable_fall_damage: false

# This feature requires EssentialsX or PremiumVanish!
# If you wish for players to bypass flight disabling while they are in vanish (or spectating), set the following option to true
vanish_bypass: false

# To use flight_trail, you MUST have a version/fork of SPIGOT (unless you are using 1.13)!
# This feature works with EssentialsX and PremiumVanish!
# If you are vanished with either of the plugins above or are in spectator mode the particles do not spawn
# Set the following value to true if you wish for cloud particles to spawn under players that are moving while flying
flight_trail: false

# Worlds that deny flight
disable_flight_worlds:
# Change exampleworld to your world below if you wish to use this feature
- exampleworld

# This feature requires WorldGuard!
# Regions that deny flight
disable_flight_regions:
  # Change exampleworld to your world and the example regions below to regions within that world if you wish to use this feature
  exampleworld:
  - exampleregion
  - exampleregion2

# This feature requires Factions (by MassiveCraft), FactionsUUID, or SavageFactions!
# The below section allows configuration of the automatic enabling/disabling of flight 
# within different categories and different permissions for each category
# There are eight types of faction territories (OWN, ALLY, TRUCE, NEUTRAL, ENEMY, WARZONE, SAFEZONE, WILDERNESS)
# Note: OWN enables flight in the player's own faction territory
factions:
  # This (example) is a category (the permission to use this category is flightcontrol.factions.example)
  example:
    # This automatically enables flight for players in the region type(s) below with the permission flightcontrol.factions.example
    auto_flight:
    - OWN
    - ALLY
    
    # This automatically disables flight for players in the region type(s) below with the permission flightcontrol.factions.example
    disable_flight:
    - ENEMY
    - WARZONE
  
  # This (example2) is a category (the permission to use this category is flightcontrol.factions.example2)
  example2:
    auto_flight:
    - SAFEZONE
    - WARZONE
    disable_flight:
    - WILDERNESS

# Custom sounds for enabling/disabling flight
sounds:
  # Please use the names from the "Sound Event" section of the table on https://minecraft.gamepedia.com/Sounds.json#Java_Edition_values
  # USE THE CORRECT TABLE (Java Edition values before 1.9) if you are using 1.8!
  disable_flight:
    # Follow the instructions above for setting the value
    value: "NONE"
    pitch: 1
    volume: 1

  enable_flight:
    # Follow the instructions above for setting the value
    value: "NONE"
    pitch: 1
    volume: 1

# If you do not wish for a message to be sent at all, set it to ""
# You can use & for color codes just like any other plugin!
messages:
  # Message when denied flight
  disable_flight: "&cYour flight has automatically been disabled!"
  
  # Message when flight is automatically enabled
  enable_flight: "&aYour flight has automatically been enabled!"

  # Message when denied permission to administrative commands
  permission_denied: "&cYou do not have permission to use this command!"

#  ____                     _         _                 
# |  _ \ ___ _ __ _ __ ___ (_)___ ___(_) ___  _ __  ___ 
# | |_) / _ \ '__| '_ ` _ \| / __/ __| |/ _ \| '_ \/ __|
# |  __/  __/ |  | | | | | | \__ \__ \ | (_) | | | \__ \
# |_|   \___|_|  |_| |_| |_|_|___/___/_|\___/|_| |_|___/

# flightcontrol.admin - Ability to use FlightControl commands (automatically given to OPs)
# flightcontrol.bypass - Bypasses all fly restrictions and always allows flight
# flightcontrol.autoflyall - Ability to automatically fly in all regions that are not disabled
# flightcontrol.autofly.WORLDNAME - Ability to fly in a certain world (replace WORLDNAME in the permission with the name of the world)
# flightcontrol.autofly.WORLDNAME.REGIONNAME - Ability to fly in a certain region (replace WORLDNAME in the permission with the name of the world and REGIONNAME with the name of the region)
# flightcontrol.factions.CATEGORY - Controls flight based upon the category (replace CATEGORY with the name of the category)