#  ___ _ _      _   _    ___         _           _
# | __| (_)__ _| |_| |_ / __|___ _ _| |_ _ _ ___| |
# | _|| | / _` | ' \  _| (__/ _ \ ' \  _| '_/ _ \ |
# |_| |_|_\__, |_||_\__|\___\___/_||_\__|_| \___/_|
#         |___/                        by Spazzinq
# Donate: https://spazzinq.org/donate
# Discord: https://spazzinq.org/discord
# Issue Tracker: https://github.com/Spazzinq/FlightControl/issues
# Spigot Page: https://www.spigotmc.org/resources/flightcontrol.55168/

# Before you leave a negative review:
# ✓ Read through ALL the information in this configuration
# ✓ Contact me on Discord (if the config does not solve your problem)
# ✓ Create an official bug report or feature request on GitHub

settings:
  # Updates the config automatically and adds new features
  auto_update: true
  # Enables flight automatically (no command necessary)
  auto_enable_flight: true
  # The default speed is 1.0 and matches Essential's /flyspeed values (decimal from 0-10)
  flight_speed: 1.0
  # Supports: CombatTagPlus, CombatLogX, CombatLogPro, AntiCombatLogging, DeluxeCombat
  # NOTE: disable flight disabling/enabling in the combat plugin's config to prevent issues
  disable_flight_in_combat: false
  # Prevents fall damage when flight is disabled mid-air by FlightControl
  prevent_fall_damage: false
  # Supports: EssentialsX, PremiumVanish, SuperVanish
  # Prevents flight disabling while in vanish
  vanish_bypass: true

# Officially Supports: Factions by MassiveCraft, FactionsUUID, SavageFactions
factions:
  # Disables flight while a faction enemy is within a certain block range (set to -1 to disable)
  # NOTE: this feature may cause performance issues on larger servers
  disable_enemy_range: -1

# "towny" requires Towny
towny:
  enable_own_town: false
  # Ignores above setting if in a war
  negate_during_war: false

# "lands" requires Lands
lands:
  enable_own_land: false

trail:
  enabled: false
  # 1.8 List: https://spazzinq.org/particles/1.8.html
  # 1.14 List: https://spazzinq.org/particles/1.14.html
  particle: "CLOUD"
  amount: 2
  # "rgb" is used with colored particles (format: "red,green,blue")
  # Color picker: https://www.google.com/search?q=color+picker
  # For one specific color, you MUST set the amount to 0 if you use
  # COLOURED_DUST on 1.8, SPELL_MOB on 1.14, SPELL_MOB_AMBIENT on 1.14, or NOTE on 1.14.
  rgb: "0,0,0"

sounds:
  # Plays the sounds on EVERY double tap of the space bar
  every_enable: false
  every_disable: false
  # Please use the sound names from the "Sound Event" column
  # 1.8 List: https://minecraft.gamepedia.com/Sounds.json/Java_Edition_values_before_1.9
  # 1.14 List: https://minecraft.gamepedia.com/Sounds.json/Java_Edition_values
  enable:
    sound: "NONE"
    pitch: 1
    volume: 1
  disable:
    sound: "NONE"
    pitch: 1
    volume: 1
  # "can_enable" and "cannot_enable" are used when "auto_enable" is false
  # or if the player disables their own flight with /fly
  can_enable:
    sound: "NONE"
    pitch: 1
    volume: 1
  cannot_enable:
    sound: "NONE"
    pitch: 1
    volume: 1

# If you don't want a message to be sent, set it to ""
messages:
  # Use the actionbar (area above hotbar) instead of chat for notifications
  actionbar: false
  flight:
    enable: "&aYour flight has been enabled."
    disable: "&cYour flight has been disabled."
    # "can_enable" and "cannot_enable" are used when "auto_enable" is false
    # or if the player disables their own flight with /fly
    can_enable: "&bYou can use /fly now."
    cannot_enable: "&cYou cannot fly right now."
  trail:
    enable: "&aYou enabled the flight trail!"
    disable: "&cYou disabled the flight trail!"
  permission_denied: "&cYou do not have permission to use this command."

#  ___               _       _
# | _ \___ _ _ _ __ (_)_____(_)___ _ _  ___
# |  _/ -_) '_| '  \| (_-<_-< / _ \ ' \(_-<
# |_| \___|_| |_|_|_|_/__/__/_\___/_||_/__/
# Replace WORLDNAME in the permission with the name of the world
#         REGIONNAME with the name of the region
#         CATEGORY with the name of the category

# Important Permissions
# flightcontrol.admin - Ability to use FlightControl administrative commands (automatically given to OPs)
# flightcontrol.bypass - Bypasses all fly restrictions and always allows flight
# flightcontrol.category.CATEGORY - Controls flight based upon the defined category
# flightcontrol.flyall - Ability to automatically fly in all regions that are not disabled
# Optional Permissions
# flightcontrol.flyspeed - Ability to set flight speed
# flightcontrol.flyspeed.others - Same as above but for other players
# flightcontrol.tempfly - Ability to give temporary flight
# flightcontrol.tempfly.others - Same as above but for other players
# flightcontrol.fly.WORLDNAME - Ability to fly in a certain world
# flightcontrol.fly.WORLDNAME.REGIONNAME - Ability to fly in a certain region
# flightcontrol.nofly.WORLDNAME - Denies flight in a certain world
# flightcontrol.nofly.WORLDNAME.REGIONNAME - Denies flight in a certain region
# flightcontrol.owntown - Ability to fly in player's own town
# flightcontrol.ownland - Ability to fly in player's own land