name: FlightControl
main: org.spazzinq.flightcontrol.FlightControl
version: ${revision}
api-version: 1.13
author: Spazzinq
description: "An elegant solution for controlling player flight"
softdepend: [AntiCombatLogging, CombatLogPro, CombatLogX, CombatTagPlus, DeluxeCombat, Essentials, Factions, PlotSquared, WorldGuard, SuperVanish, PremiumVanish, Towny, Lands]

commands:
  flightcontrol:
    description: FlightControl administration
    aliases: [fc]
  fly:
    description: Toggles flight
    aliases: [fcfly, ffly]
  toggletrail:
    description: Per-player trail toggle
    aliases: [trail, tt]
  tempfly:
    description: Allows temporary bypass flight until the next server restart
    aliases: [tfly]


permissions:
  flightcontrol.fly:
    description: Access to the fly command when the command option is enabled in the config
    default: false
  flightcontrol.owntown:
    description: Enables flight in player's own town
    default: false
  flightcontrol.ownland:
    description: Enables flight in player's own land
    default: false
  flightcontrol.flyall:
    description: Ability to automatically fly in all regions that are not disabled
    default: false
  flightcontrol.bypass:
    description: Bypasses all fly restrictions and always allows flight
    default: false
  flightcontrol.bypasstemp:
    description: Same function as bypass permission, but meant to be temporary
  flightcontrol.flyother:
    description: Ability to enable another player's fly and bypass all restrictions (like bypass permission) until server restart
    default: false
  flightcontrol.admin:
    description: Ability to use FlightControl administrative commands (automatically given to OPs)
    default: op